In [31]:
#installer
# BW:
# top seller actual
# 1000 reviews 333 je category
!pip install spicy

Collecting spicy
  Downloading spicy-0.16.0-py2.py3-none-any.whl (1.7 kB)
Requirement already satisfied: scipy in c:\users\bernhard\appdata\local\programs\python\python38\lib\site-packages (from spicy) (1.10.1)
Requirement already satisfied: numpy<1.27.0,>=1.19.5 in c:\users\bernhard\appdata\local\programs\python\python38\lib\site-packages (from scipy->spicy) (1.24.3)
Installing collected packages: spicy
Successfully installed spicy-0.16.0

WARNING: You are using pip version 20.2.3; however, version 23.2.1 is available.
You should consider upgrading via the 'c:\users\bernhard\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.

### TF-IDF

In [14]:
import sqlite3
import pandas as pd

In [15]:
def get_data_from_database():
    conn = sqlite3.connect('../data/db_steam.db')
    df = pd.read_sql('SELECT * FROM reviews', conn)
    conn.close()
    return df

df = get_data_from_database()

In [36]:
#tfidf of reviews
from sklearn.feature_extraction.text import TfidfVectorizer

# Create an instance of TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()

# Fit the vectorizer to the text data and transform it into TF-IDF vectors
tfidf_vectors = tfidf_vectorizer.fit_transform(df['review_clean'])

# Convert the TF-IDF vectors to an array
tfidf_array = tfidf_vectors.toarray()

# Get the feature names (words)
feature_names = tfidf_vectorizer.get_feature_names_out()

# Create a DataFrame for better visualization (optional)
import pandas as pd
tfidf_df = pd.DataFrame(tfidf_array, columns=feature_names)

tfidf_array.shape

MemoryError: Unable to allocate 43.4 GiB for an array with shape (87271, 66760) and data type float64

In [37]:
#tfidf of reviews
from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.sparse import csr_matrix

# Create an instance of TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()

tfidf_vectors = tfidf_vectorizer.fit_transform(df['review_clean'])

feature_names = tfidf_vectorizer.get_feature_names_out()

tfidf_csr_matrix = csr_matrix(tfidf_vectors)

tfidf_dataframe = pd.DataFrame.sparse.from_spmatrix(tfidf_csr_matrix, columns=feature_names)

tfidf_dataframe

,000kxooxwnk,000s,00225fc9,00oxnnnwx0xkd,00s,00x00000001,01oct,01s,02h,02hrs,...,𝙣𝙚𝙬,𝙤𝙛,𝙩𝙝𝙚,𝙩𝙝𝙞𝙨,𝙬𝙖𝙣𝙩,𝙬𝙝𝙚𝙣,𝙬𝙝𝙤𝙚𝙫𝙚𝙧,𝙬𝙤𝙧𝙡𝙙,𝙮𝙤𝙪,𝟽ᴅᴀʏs
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87266,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
87267,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
87268,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
87269,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
87270,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [39]:
sorted_tfidf_dataframe = tfidf_dataframe.sort_values(by=feature_names[0], ascending=False)

top_document = sorted_tfidf_dataframe.iloc[0]

top_words = top_document.sort_values(ascending=False).head(20)

In [40]:
top_words

mmmmmmmmo                                                     0.177298
lc                                                            0.171145
000kxooxwnk                                                   0.088649
c0kkcxocd                                                     0.088649
xoxkxdlokokxlok00kwwwxkkx                                     0.088649
knnwnnwmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm                  0.088649
xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm                             0.088649
cokdc                                                         0.088649
d0onxnwwwkk00                                                 0.088649
okkxnxdlxwmmmmmmm                                             0.088649
lok0knndkxwmmmmmmmmmmmmm                                      0.088649
oknwwknwnxok                                                  0.088649
cxxxkk0xwmwnwmmmmmmmmmmmmmmmm                                 0.088649
cx0dkmmmmmmm                                                  0.088649
lcccldxwn00xcolkwmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm    0.088649
lcdkwwwnk00o                                                  0.088649
clc                                                           0.088649
dx00dxokdxokno                                                0.088649
mmmmmmmmmmwo                                                  0.088649
mmmmmmmwxcloknn0kxdko                                         0.088649
Name: 49183, dtype: Sparse[float64, 0]

In [51]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(df['review_clean'])
feature_names = tfidf_vectorizer.get_feature_names_out()

tfidf_scores_df = pd.DataFrame({'Wort': feature_names, 'TF-IDF-Score': tfidf_matrix.mean(axis=0).tolist()[0]})
tfidf_scores_df = tfidf_scores_df.sort_values(by='TF-IDF-Score', ascending=False)
tfidf_scores_df.head(20)

           Wort  TF-IDF-Score
22510      game      0.077004
23824      good      0.051514
22157       fun      0.033322
24267     great      0.020507
32417      like      0.020112
38880       one      0.019681
41696      play      0.018567
33119      love      0.015807
6617       best      0.015617
55344      time      0.013916
23325       get      0.013666
3607        and      0.012287
44813    really      0.011755
59504        wa      0.011627
37430      nice      0.010928
55056  thousand      0.010835
61638       yes      0.010380
61131     would      0.010277
56816       two      0.010240
54485       ten      0.010058

# HELP